### ISSUE TITLE
Error on run in 1.7.0

### ISSUE THREAD

**Issue by clehner** [dominictarr/patchbay#32]
```
Uncaught TypeError: Cannot read property 'port' of undefined
  module.exports @ /usr/local/src/patchbay/node_modules/ssb-client/index.js:54
  (anonymous function) @ /usr/local/src/patchbay/sbot-api.js:38
  module.exports @ /usr/local/src/patchbay/node_modules/pull-reconnect/index.js:67
  module.exports @ /usr/local/src/patchbay/sbot-api.js:33
  (anonymous function) @ /usr/local/src/patchbay/index.js:21
 ```

**Comment by clehner** [comment]
I got passed that and then got this:
```
/usr/local/src/patchbay/sbot-api.js:43 Error: could not connect to sbot
    at /usr/local/src/patchbay/node_modules/ssb-client/index.js:87:23
    at Object.client (/usr/local/src/patchbay/node_modules/ssb-client/node_modules/multiserver/index.js:25:12)
  Error: could not connect to one of:net:localhost:undefined~shs:f/6sQ6d2CMxRUhLpspgGIulDxDCwYD7DzFzPNr7u5AU=
    at Object.client (/usr/local/src/patchbay/node_modules/ssb-client/node_modules/multiserver/index.js:25:15)
    at module.exports (/usr/local/src/patchbay/node_modules/ssb-client/index.js:86:6)
    at /usr/local/src/patchbay/sbot-api.js:38:5
    at module.exports (/usr/local/src/patchbay/node_modules/pull-reconnect/index.js:67:3)
    at module.exports (/usr/local/src/patchbay/sbot-api.js:33:13)
    at Object.<anonymous> (/usr/local/src/patchbay/index.js:21:17)
```

Hmmmmmm...

**Comment by evbogue** [comment]
I'm getting this error too.

**Comment by dominictarr** [comment]
oops, I just pushed ssb-client@4.0.1, I think that should fix it.

**Comment by evbogue** [comment]
@dominictarr Now I'm getting `Uncaught TypeError: int.unref is not a function` after installing ssb-client@latest.

**Comment by clehner** [comment]
I don't see ssb-client@4.0.1 on npm or github

**Comment by clehner** [comment]
Reverting 903fcd29d3f44795fe947a4f12ab38ea616adb6c fixed this for me

**Comment by dominictarr** [comment]
sorry, this is published now!

**Comment by evbogue** [comment]
Fixed.
